package JavaDasar;

import java.util.Scanner;

public class Exception {
    public static void main(String[] args) {
        //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.
        //Exception handling (try, catch ,dan finaly)
        //exception handling fungsinya agar program dibawahnya tetep dieksekusi walaupun ada error, (dan errornya kita modifikasi jika terjadi maka lakukan hal lain

//        int [] arry = {1,2,3,4,5};
//        Scanner inputUser= new Scanner(System.in);
//        int index = inputUser.nextInt();
//
//        try { // kita akses arry, jika melebihi index (err kita tangkap)//
//            System.out.printf("index ke -%d adalah %d",index,arry[index]);
//        }catch (java.lang.Exception e){
//            System.out.println("ada kesalahan");
//        } finally {
//            System.out.println(" \nsalah ga salah finnaly tetap dilakukan");
//        }
//
//        System.out.println("program selesai");
        //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        //trow exceptio(by class, by method)  kelas terbuka java episode 53. untuk lebih jelas


    }
}
